"""
Crisis-safety layer for the AI wellbeing companion chat.

This module is intentionally separate from the model call: crisis
resources are returned by pattern-matching, NOT generated by the LLM, so
they are always accurate and always shown the moment a risk signal
appears — regardless of what the model itself says.

Keep this list conservative (favor false positives over false negatives):
better to show a helpline banner to someone who didn't need it than to
miss someone who did.
"""

from __future__ import annotations

import re
from typing import Dict, List

# Verified as of July 2026. Re-check periodically — these numbers/services
# can change.
CRISIS_RESOURCES: Dict[str, Dict[str, object]] = {
    "el": {
        "intro": "Αν αυτή τη στιγμή σκέφτεσαι να βλάψεις τον εαυτό σου ή διατρέχεις κίνδυνο, σε παρακαλώ μίλησε με κάποιον αμέσως — δεν χρειάζεται να το αντιμετωπίσεις μόνος/η σου:",
        "lines": [
            "Γραμμή Παρέμβασης για την Αυτοκτονία (ΚΛΙΜΑΚΑ) — 1018, 24/7, δωρεάν, εμπιστευτικά",
            "Γραμμή Ψυχοκοινωνικής Υποστήριξης — 10306, 24/7, δωρεάν",
            "Ευρωπαϊκός αριθμός έκτακτης ανάγκης — 112",
        ],
    },
    "en": {
        "intro": "If you're thinking about harming yourself or you're in danger right now, please reach out immediately — you don't have to go through this alone:",
        "lines": [
            "US / Canada: call or text 988 (Suicide & Crisis Lifeline), 24/7",
            "UK / ROI: call 116 123 (Samaritans), 24/7, free",
            "Elsewhere: contact your local emergency number, or find a helpline near you at befrienders.org",
        ],
    },
    "es": {
        "intro": "Si estás pensando en hacerte daño o corres peligro ahora mismo, por favor busca ayuda de inmediato — no tienes que pasar por esto solo/a:",
        "lines": [
            "España: llama al 024, Línea de Atención a la Conducta Suicida — 24/7, gratuita y confidencial",
            "Emergencias — 112",
            "Otro país: busca una línea de ayuda cercana en befrienders.org",
        ],
    },
    "default": {
        "intro": "If you're thinking about harming yourself or you're in danger right now, please reach out immediately — you don't have to go through this alone:",
        "lines": [
            "Contact your local emergency number right away",
            "Find a crisis line near you at befrienders.org (international directory)",
        ],
    },
}


# Deliberately broad, common phrases — not an exhaustive clinical list.
# Word-boundary matched, case-insensitive.
_CRISIS_PATTERNS: Dict[str, List[str]] = {
    "en": [
        r"kill myself", r"end my life", r"suicidal", r"want to die",
        r"don'?t want to (live|be alive)", r"no reason to live",
        r"self.?harm", r"hurt myself", r"cut myself", r"better off dead",
        r"end it all",
    ],
    "el": [
        r"να\s+αυτοκτον\w*", r"αυτοκτον\w*", r"θέλω να πεθάνω",
        r"δεν θέλω να ζω", r"να τελειώσω τη ζωή μου",
        r"να κάνω κακό στον εαυτό μου", r"να πληγωθώ",
    ],
    "es": [
        r"suicid\w*", r"quiero morir", r"no quiero vivir",
        r"acabar con mi vida", r"hacerme daño", r"lastimarme",
    ],
}
_CRISIS_RE = {
    lang: re.compile("|".join(pats), re.IGNORECASE | re.UNICODE)
    for lang, pats in _CRISIS_PATTERNS.items()
}


def detect_crisis(text: str, lang_code: str = "en") -> bool:
    """Check the given text (any language we have patterns for, plus
    always English as a fallback since crisis phrases sometimes get
    typed in English regardless of the surrounding UI language)."""
    if not text:
        return False
    patterns_to_check = {lang_code, "en"}
    for lang in patterns_to_check:
        rx = _CRISIS_RE.get(lang)
        if rx and rx.search(text):
            return True
    return False


def crisis_resources_for(lang_code: str) -> Dict[str, object]:
    return CRISIS_RESOURCES.get(lang_code, CRISIS_RESOURCES["default"])
